### PR TITLE
remove placeholders and add your copyright to the apache license

### PR DESCRIPTION
**Pull request by soldair**

### CODE REVIEW

**Comment by lovell** [comment]
Hi Ryan, thanks for the PR, is this proposal based on some form of legal request?

This "boilerplate" text is part of the appendix that explains how to apply the Apache 2.0 license and appears after the "END OF TERMS AND CONDITIONS" statement. As far as I understand these placeholders are not part of the license itself and do not require populating.

The README.md in this repo contains the copyright statement and this file is also published to npm. Is there perhaps somewhere else it should also appear? I'm aware that the source files are missing a copyright header so that could be a better/alternative place to address this.

**Comment by soldair** [comment]
Hey. The tools that verify/lint os licenses at google reported an error so instead of working around it in the future I figured I'd help other fellows out.

I cant debate the correctness or usefulness of the check process itself. I'm just shoveling code over here in the mines ;)

**Comment by lovell** [comment]
Thanks, are you able to provide the complete output of the tooling error to help me understand how better to fix this situation?

Based on my understanding of copyright and licensing law in common law countries such as the UK and USA, the proposed change in this PR suggests the tooling at Google is not only broken but might be making things legally more ambiguous. Of course I may be wrong and am happy to engage lawyers that understand this situation better than I do.

**Comment by soldair** [comment]
Hey, I'm engaging in good faith here. Also 
I honestly don't think its possible for me to hire you a lawyer to give you legal advice. 

Filling out the placeholders for your name and copyright date in the Apache license template seems uncontroversial. Just like you add your name to the MIT license.

If you're not interested in this change just close it. No worries.

**Comment by lovell** [comment]
Apologies for the heavy-handed language, your PR is received with good faith, thank you.

I've done some legal research and asked a few people with greater experience of software licensing. 

Where licenses such as MIT provide placeholders for copyright details, the Apache 2.0 license differs in that it provides an appendix with an example for how to apply it to source files.

This appendix is not part of the license so can be removed in its entirety, however, rather amazingly, amending this appendix _might_ constitute a copyright infringement (this is the sort of thing I learn when I ask for legal advice).

Removing the appendix can break some tooling that expects it to be there. Here's an example of a recent change by a Google employee to ensure the complete, original appendix is present in the Apache 2.0 license on a Google-owned repository - https://github.com/google/blockly/pull/2754

What the Apache 2.0 license does provide for is an optional NOTICES file to contain copyright details such as year and name. I'd be very happy to include such a file in this repo if it helps tooling detect and/or enforce open source licenses.

http://www.apache.org/dev/licensing-howto.html

**Comment by soldair** [comment]
this is really interesting. It seems like i was wrong about why the error appeared because my change is clearly wrong.

**Pull request closed without merging**
