### PR TITLE
enhancement of integration tests

### PR DESCRIPTION
**Pull request by coreprocess**
Includes the following test environments:
- alpinelinux-3.2-nodejs-0.10.x
- alpinelinux-3.2-nodejs-8.x
- alpinelinux-3.3-nodejs-0.10.x
- alpinelinux-3.3-nodejs-8.x
- alpinelinux-3.4-nodejs-0.10.x
- alpinelinux-3.4-nodejs-8.x
- alpinelinux-3.5-nodejs-0.10.x
- alpinelinux-3.5-nodejs-8.x
- alpinelinux-3.6-nodejs-0.10.x
- alpinelinux-3.6-nodejs-8.x
- amazonlinux-2016.09-nodejs-0.10.x
- amazonlinux-2016.09-nodejs-8.x
- amazonlinux-2017.03-nodejs-0.10.x
- amazonlinux-2017.03-nodejs-8.x
- amazonlinux-2017.09-nodejs-0.10.x
- amazonlinux-2017.09-nodejs-8.x
- centos-6.6-nodejs-0.10.x
- centos-6.6-nodejs-8.x
- centos-6.7-nodejs-0.10.x
- centos-6.7-nodejs-8.x
- centos-6.8-nodejs-0.10.x
- centos-6.8-nodejs-8.x
- centos-6.9-nodejs-0.10.x
- centos-6.9-nodejs-8.x
- centos-7.0-nodejs-0.10.x
- centos-7.0-nodejs-8.x
- centos-7.1-nodejs-0.10.x
- centos-7.1-nodejs-8.x
- centos-7.2-nodejs-0.10.x
- centos-7.2-nodejs-8.x
- centos-7.3-nodejs-0.10.x
- centos-7.3-nodejs-8.x
- centos-7.4-nodejs-0.10.x
- centos-7.4-nodejs-8.x
- debian-jessie-nodejs-0.10.x
- debian-jessie-nodejs-8.x
- debian-stretch-nodejs-8.x
- debian-wheezy-nodejs-0.10.x
- opensuse-42.2-nodejs-4.x
- opensuse-42.3-nodejs-4.x
- opensuse-tumbleweed-nodejs-4.x
- oraclelinux-6.6-nodejs-0.10.x
- oraclelinux-6.6-nodejs-8.x
- oraclelinux-6.7-nodejs-0.10.x
- oraclelinux-6.7-nodejs-8.x
- oraclelinux-6.8-nodejs-0.10.x
- oraclelinux-6.8-nodejs-8.x
- oraclelinux-6.9-nodejs-0.10.x
- oraclelinux-6.9-nodejs-8.x
- oraclelinux-7.0-nodejs-0.10.x
- oraclelinux-7.0-nodejs-8.x
- oraclelinux-7.1-nodejs-0.10.x
- oraclelinux-7.1-nodejs-8.x
- oraclelinux-7.2-nodejs-0.10.x
- oraclelinux-7.2-nodejs-8.x
- oraclelinux-7.3-nodejs-0.10.x
- oraclelinux-7.3-nodejs-8.x
- oraclelinux-7.4-nodejs-0.10.x
- oraclelinux-7.4-nodejs-8.x
- ubuntu-14.04-nodejs-0.10.x
- ubuntu-14.04-nodejs-8.x
- ubuntu-16.04-nodejs-0.10.x
- ubuntu-16.04-nodejs-0.12.x
- ubuntu-16.04-nodejs-4.x
- ubuntu-16.04-nodejs-6.x
- ubuntu-16.04-nodejs-8.x
- ubuntu-17.04-nodejs-8.x
- ubuntu-17.10-nodejs-8.x

### CODE REVIEW

**Comment by coreprocess** [comment]
https://circleci.com/gh/core-process/detect-libc/40

image

**Comment by coreprocess** [comment]
You will find the test specification here:
- [tests/integration/spec.json](https://github.com/core-process/detect-libc/blob/feature/enhanced-integration-test/tests/integration/spec.json)
- [tests/integration/spec/](https://github.com/core-process/detect-libc/tree/feature/enhanced-integration-test/tests/integration/spec)

The tests representing the Node.js version dimension are here:
- [tests/integration/spec.json#L2](https://github.com/core-process/detect-libc/blob/feature/enhanced-integration-test/tests/integration/spec.json#L2)
- [tests/integration/spec.json#L51](https://github.com/core-process/detect-libc/blob/feature/enhanced-integration-test/tests/integration/spec.json#L51)
- [tests/integration/spec.json#L62](https://github.com/core-process/detect-libc/blob/feature/enhanced-integration-test/tests/integration/spec.json#L62)

**Comment by coreprocess** [comment]
Pre-built images are currently stored at [quay.io/core_process/detect-libc-integration-test](http://quay.io/core_process/detect-libc-integration-test). We can change the location anytime.

**Comment by lovell** [comment]
Wow, this is seriously comprehensive, thank you Niklas. Feel free to merge this in when you're ready.

**Comment by lovell** [comment]
Would it be possible for you to grant push access to the `detect-libc-integration-test` repo for my quay.io `lovell` account?

**Comment by coreprocess** [comment]
@lovell I granted admin access to the repository.
If you want to "move" the repository to your account, just let me know (whatever you feel is better for the management of the project). Once you created a repository at your account and granted push access I can push all pre-built images from my computer to your repository.

**Comment by lovell** [comment]
Thanks for merging - I'm happy to use the repo in your quay account.

**Pull request merged**
